---
- name: Gather facts
  hosts: all
  gather_facts: true

- name: Converge
  hosts: unbound
  roles:
    - role: unbound
      vars:
        unbound_listen_ips:
          - "{{ ansible_default_ipv4.address }}"
          - "{{ ansible_default_ipv6.address }}"
        unbound_private_domain: example.org
        unbound_public_dns_servers:
          - 8.8.8.8
          - 8.8.4.4
        unbound_private_dns_servers:
          - "{{ hostvars['dhcp-ddns'].ansible_default_ipv4.address }}"
        unbound_allow_subnets:
          - "{{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) | ipaddr('network/prefix') }}"
          - "{{ ansible_default_ipv6.address }}/{{ ansible_default_ipv6.prefix }}"
